# Generated by Django 5.1.4 on 2025-02-01 09:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'A user with the provided phone number already exists'}, help_text='Enter a valid phone number', max_length=128, region=None, unique=True),
        ),
    ]
