# Generated by Django 5.1.4 on 2025-02-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patients',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
