# Generated by Django 5.1.4 on 2025-02-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='patients',
        ),
    ]
