# Generated by Django 5.1.4 on 2025-03-05 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0045_alter_branch_phonenumber'),
        ('users', '0006_remove_user_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='custom_admin.branch'),
        ),
    ]
