# Generated by Django 5.1.4 on 2025-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credential',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='credentialStatus',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='dateEmployed',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employmentStatus',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
