# Generated by Django 5.1.4 on 2025-03-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_credential_user_credentialstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maritalStatus',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
