# Generated by Django 5.1.4 on 2025-03-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_maritalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employmentStatus',
            field=models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('dismissed', 'Dismissed')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
