# Generated by Django 5.1.4 on 2025-02-01 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facilityId', models.AutoField(primary_key=True, serialize=False)),
                ('facilityName', models.CharField(max_length=255)),
                ('facilityAddress', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medicationId', models.AutoField(primary_key=True, serialize=False)),
                ('medicationName', models.CharField(max_length=255)),
                ('medicationCode', models.CharField(max_length=50)),
                ('equivalentTo', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('quantity', models.CharField(max_length=255)),
                ('diagnosis', models.TextField()),
                ('medicationTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active Medication'), ('stale', 'Stale Medication')], default='active', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchId', models.AutoField(primary_key=True, serialize=False)),
                ('branchName', models.CharField(max_length=255)),
                ('branchAddress', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='custom_admin.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.FileField(blank=True, default=None, null=True, upload_to='patients')),
                ('firstName', models.CharField(max_length=255)),
                ('middleNames', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('diagnosis', models.TextField()),
                ('allergies', models.TextField()),
                ('physicianName', models.CharField(max_length=255)),
                ('pcpOrDoctor', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('cart', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='custom_admin.branch')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('medicationAdministrationId', models.AutoField(primary_key=True, serialize=False)),
                ('timeAdministered', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('careGiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_ad', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_ad', to='custom_admin.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_ad', to='custom_admin.patient')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='custom_admin.patient'),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chartId', models.AutoField(primary_key=True, serialize=False)),
                ('behaviors', models.JSONField()),
                ('behaviorsDescription', models.JSONField()),
                ('dateTaken', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('careGiver1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_care_giver', to=settings.AUTH_USER_MODEL)),
                ('careGiver2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_care_giver', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='custom_admin.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('updateId', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField()),
                ('dateTaken', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('careGiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='custom_admin.patient')),
            ],
        ),
    ]
