# Generated by Django 5.1.4 on 2025-02-02 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('chartDataId', models.AutoField(primary_key=True, serialize=False)),
                ('behaviors', models.JSONField()),
                ('behaviorsDescription', models.JSONField()),
                ('timeToBeTaken', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts_data', to='custom_admin.patient')),
            ],
        ),
    ]
