# Generated by Django 5.1.4 on 2025-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_chartdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facilityName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
