# Generated by Django 5.1.4 on 2025-02-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_facility_facilityname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facilityName',
            field=models.CharField(max_length=255),
        ),
    ]
