# Generated by Django 5.1.4 on 2025-02-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_alter_chartdata_behaviorsdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='behaviorsDescription',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
