# Generated by Django 5.1.4 on 2025-02-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_alter_chartdata_behaviorsdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='behaviorsDescription',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
