# Generated by Django 5.1.4 on 2025-02-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_alter_chart_behaviorsdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='dateTaken',
            field=models.DateTimeField(),
        ),
    ]
