# Generated by Django 5.1.4 on 2025-02-02 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_alter_chart_datetaken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='careGiver1',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='careGiver2',
        ),
        migrations.AddField(
            model_name='chart',
            name='careGiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='charts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
