# Generated by Django 5.1.4 on 2025-02-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0009_remove_chart_caregiver1_remove_chart_caregiver2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicationTime',
            field=models.TimeField(),
        ),
    ]
