# Generated by Django 5.1.4 on 2025-02-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0010_alter_medication_medicationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='timeToBeTaken',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='timeAdministered',
            field=models.TimeField(),
        ),
    ]
