# Generated by Django 5.1.4 on 2025-02-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0011_alter_chartdata_timetobetaken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('approved', 'Approved')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('approved', 'Approved')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='update',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('approved', 'Approved')], default='pending', max_length=50),
        ),
    ]
