# Generated by Django 5.1.4 on 2025-02-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0012_chart_status_medicationadministration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='reasonNotFiled',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='reasonNotFiled',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='reasonNotFiled',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
