# Generated by Django 5.1.4 on 2025-02-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0014_patientmanager'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together={('patient', 'dateTaken')},
        ),
    ]
