# Generated by Django 5.1.4 on 2025-02-08 10:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0015_alter_chart_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientmanager',
            unique_together={('patient', 'careGiver')},
        ),
    ]
