# Generated by Django 5.1.4 on 2025-02-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0017_alter_chart_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together={('patient', 'dateTaken')},
        ),
    ]
