# Generated by Django 5.1.4 on 2025-02-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0018_alter_chart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='vitals',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='vitals',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
