# Generated by Django 5.1.4 on 2025-02-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0019_chart_vitals_chartdata_vitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='medicationTime',
        ),
    ]
