# Generated by Django 5.1.4 on 2025-02-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0020_remove_medication_medicationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='medicationTime',
            field=models.JSONField(default=list),
        ),
    ]
