# Generated by Django 5.1.4 on 2025-02-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0021_medication_medicationtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('weeeklyAppointments', models.JSONField(blank=True, default=list, null=True)),
                ('fortnightAppoints', models.JSONField(blank=True, default=list, null=True)),
                ('monthlyAppoints', models.JSONField(blank=True, default=list, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='custom_admin.patient')),
            ],
        ),
    ]
