# Generated by Django 5.1.4 on 2025-02-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0022_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='fortnightAppoints',
            new_name='fortnightAppointments',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='monthlyAppoints',
            new_name='monthlyAppointments',
        ),
    ]
