# Generated by Django 5.1.4 on 2025-02-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0023_rename_fortnightappoints_appointment_fortnightappointments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='weeeklyAppointments',
            new_name='weeklyAppointments',
        ),
    ]
