# Generated by Django 5.1.4 on 2025-02-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0024_rename_weeeklyappointments_appointment_weeklyappointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationadministration',
            name='timeAdministered',
        ),
    ]
