# Generated by Django 5.1.4 on 2025-02-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0027_update_type_update_weight_update_weightdeviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attendedTo',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
