# Generated by Django 5.1.4 on 2025-02-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0028_appointment_attendedto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationadministration',
            name='reasonNotFiled',
        ),
        migrations.RemoveField(
            model_name='medicationadministration',
            name='status',
        ),
    ]
