# Generated by Django 5.1.4 on 2025-02-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0029_remove_medicationadministration_reasonnotfiled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationadministration',
            name='timeAdministered',
        ),
    ]
