# Generated by Django 5.1.4 on 2025-02-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0030_remove_medicationadministration_timeadministered'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministration',
            name='timeAdministered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
