# Generated by Django 5.1.4 on 2025-02-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0031_medicationadministration_timeadministered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='status',
        ),
    ]
