# Generated by Django 5.1.4 on 2025-02-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0032_remove_medication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='reasonNotFiled',
        ),
        migrations.RemoveField(
            model_name='update',
            name='status',
        ),
    ]
