# Generated by Django 5.1.4 on 2025-02-20 14:50

from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0033_remove_update_reasonnotfiled_remove_update_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='attendedTo',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='fortnightAppointments',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='monthlyAppointments',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='weeklyAppointments',
        ),
        migrations.AddField(
            model_name='appointment',
            name='dateTaken',
            field=models.DateField(default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='nextAppointmentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('Primary Care Provider (PCP)', 'Primary Care Provider (PCP)'), ('Mental Health Provider / Physician/ Prescriber', 'Mental Health Provider / Physician/ Prescriber'), ('Clinician', 'Clinician'), ('Peer Support Counsellor', 'Peer Support Counsellor'), ('Counsellor', 'Counsellor'), ('Dentist', 'Dentist'), ('Specialist', 'Specialist'), ('Other', 'Other')], default="Other", max_length=200),
            preserve_default=False,
        ),
    ]
