# Generated by Django 5.1.4 on 2025-02-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0034_remove_appointment_attendedto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='reasonNotFiled',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='status',
        ),
    ]
