# Generated by Django 5.1.4 on 2025-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0035_remove_chart_reasonnotfiled_remove_chart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministration',
            name='status',
            field=models.CharField(choices=[('removed', 'Removed'), ('paused', 'Paused'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
