# Generated by Django 5.1.4 on 2025-02-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0036_medicationadministration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationadministration',
            name='status',
        ),
        migrations.AddField(
            model_name='medication',
            name='status',
            field=models.CharField(choices=[('removed', 'Removed'), ('paused', 'Paused'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
