# Generated by Django 5.1.4 on 2025-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0039_patient_clinician_alter_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cart',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='room',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
