# Generated by Django 5.1.4 on 2025-03-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0040_alter_patient_cart_alter_patient_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('vitalId', models.AutoField(primary_key=True, serialize=False)),
                ('bloodPressure', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('pulse', models.FloatField()),
                ('oxygenSaturation', models.FloatField()),
                ('pain', models.TextField()),
                ('dateTaken', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='custom_admin.patient')),
            ],
        ),
    ]
