# Generated by Django 5.1.4 on 2025-03-05 07:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0043_patient_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, default=None, error_messages={'unique': 'A branch with that email already exists.'}, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='fax',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, error_messages={'unique': 'A branch with the provided phone number already exists'}, help_text='Enter a valid phone number', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='nextAppointmentDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
