# Generated by Django 5.1.4 on 2025-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0044_branch_email_branch_fax_branch_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phoneNumber',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'A branch with the provided phone number already exists'}, help_text='Enter a valid phone number', null=True, unique=True),
        ),
    ]
