# Generated by Django 5.1.4 on 2025-03-06 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0045_alter_branch_phonenumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LateSubmission',
            fields=[
                ('lateSubmissionId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('charts', 'Charts'), ('medication', 'Medication'), ('weekly update', 'Weekly Updates'), ('monthly update', 'Monthly Update'), ('vital', 'Vital')], max_length=50)),
                ('start', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('reasonForLateSubmission', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('careGiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_late_submissions', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_late_submissions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_submissions', to='custom_admin.patient')),
            ],
        ),
    ]
