# Generated by Django 5.1.4 on 2025-03-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0047_chart_reasonedited'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='reasonEdited',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
