# Generated by Django 5.1.4 on 2025-03-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0048_vital_reasonedited'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='reasonFilledLate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
