# Generated by Django 5.1.4 on 2025-03-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0049_chart_reasonfilledlate'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='reasonEdited',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='reasonFilledLate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
