# Generated by Django 5.1.4 on 2025-03-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0050_update_reasonedited_update_reasonfilledlate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latesubmission',
            name='type',
            field=models.CharField(choices=[('charts', 'Charts'), ('medication', 'Medication'), ('updates', 'Updates'), ('vital', 'Vital')], max_length=50),
        ),
    ]
