# Generated by Django 5.1.4 on 2025-03-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0051_alter_latesubmission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='declineReason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=50),
        ),
    ]
