# Generated by Django 5.1.4 on 2025-03-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0052_chart_declinereason_chart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('updated', 'Updated')], default='pending', max_length=50),
        ),
    ]
