# Generated by Django 5.1.4 on 2025-03-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0053_alter_chart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='declineReason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('updated', 'Updated')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='vital',
            name='declineReason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vital',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('updated', 'Updated')], default='pending', max_length=50),
        ),
    ]
