# Generated by Django 5.1.4 on 2025-03-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0054_update_declinereason_update_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='reasonFilledLate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
