# Generated by Django 5.1.4 on 2025-03-11 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0055_vital_reasonfilledlate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='careGiver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chart',
            name='careGiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to=settings.AUTH_USER_MODEL),
        ),
    ]
