# Generated by Django 5.1.4 on 2025-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0056_vital_caregiver_alter_chart_caregiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='reasonNotFilled',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='reasonNotFilled',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vital',
            name='reasonNotFilled',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
