# Generated by Django 5.1.4 on 2025-03-15 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0058_leave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('utilityId', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('addressed', 'Addressed'), ('review', 'Review'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
