# Generated by Django 5.1.4 on 2025-03-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0059_utility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
