# Generated by Django 5.1.4 on 2025-03-17 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0060_alter_utility_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('groceryId', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.JSONField(default=list)),
                ('feedback', models.TextField(blank=True, default=None, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groceries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
