# Generated by Django 5.1.4 on 2025-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0061_grocery'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('updated', 'Updated')], default='pending', max_length=50),
        ),
    ]
