# Generated by Django 5.1.4 on 2025-03-17 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0062_grocery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groceries', to='custom_admin.branch'),
        ),
    ]
