# Generated by Django 5.1.4 on 2025-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0063_grocery_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('updated', 'Updated'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
