# Generated by Django 5.1.4 on 2025-03-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0065_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessmentId', models.AutoField(primary_key=True, serialize=False)),
                ('assessmentStartDate', models.DateField(default=None, null=True)),
                ('assessmentNextDate', models.DateField(default=None, null=True)),
                ('NCPStartDate', models.DateField(default=None, null=True)),
                ('NCPNextDate', models.DateField(default=None, null=True)),
                ('socialWorker', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='custom_admin.patient')),
            ],
        ),
    ]
