# Generated by Django 5.1.4 on 2025-04-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0067_sleep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleep',
            old_name='incidentId',
            new_name='sleepId',
        ),
    ]
