# Generated by Django 5.1.4 on 2025-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0068_rename_incidentid_sleep_sleepid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='reasonFilledLate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
