# Generated by Django 5.1.4 on 2025-04-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0069_sleep_reasonfilledlate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='markAs',
            field=models.CharField(choices=[('A', 'Awake'), ('S', 'Sleeping'), ('N/A', 'Not Applicable')], max_length=50),
        ),
    ]
