# Generated by Django 5.1.4 on 2025-05-19 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0070_alter_sleep_markas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='details',
            new_name='incident',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='staff',
        ),
        migrations.AddField(
            model_name='incident',
            name='assignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='comments',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='raisedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_raised_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolvedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in progress', 'In Progress'), ('closed', 'Closed')], default='pending', max_length=50),
        ),
    ]
