# Generated by Django 5.1.4 on 2025-05-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0071_rename_details_incident_incident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident',
            field=models.TextField(default=list),
        ),
    ]
