from custom_admin.models.branch import Branch
from custom_admin.models.facility import Facility
from custom_admin.models.chart import Chart
from custom_admin.models.medical_administration import MedicationAdministration
from custom_admin.models.medication import Medication
from custom_admin.models.patient import Patient
from custom_admin.models.update import Update
from custom_admin.models.chart_data import ChartData
from custom_admin.models.patient_manager import PatientManager
from custom_admin.models.appointment import Appointment
from custom_admin.models.vitals import Vital
from custom_admin.models.late_submission import LateSubmission